### PR TITLE
Add LLM judge scoring for chat

### PR DESCRIPTION
**Pull request by abeatrix**
Adding LLM judge score for chat leaderboard

image

### CODE REVIEW

**Comment by abeatrix** [comment]
@jtibshirani this is the PR you can build the new UI on 😄

**Review by jtibshirani — APPROVED** [review]
I tried this out locally and it looks great. I had a couple small comments:
* It'd be great if the dropdown ordered the questions the same as the LLM judge table.
* In a follow-up, maybe we can label each response with the LLM judge's output! I would find this very useful. To clarify what I mean, we could put it here...
Screenshot 2024-06-25 at 4 57 35 PM

**Comment by jtibshirani** [comment]
I pushed some updates directly, hope you don't mind!

**Comment by abeatrix** [comment]
as discussed with @jtibshirani , i am running into issue with re-running the tests so we will merge what we have now and update the prompt and scoring in follow up PRs

**Pull request merged**
